export const productData = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/5490059/pexels-photo-5490059.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "Cozy Knit Sweater",
    size: "Small",
    color: "Beige",
    category: "Women's Sweaters",
    price: "$40.43",
    brand: "Knitwear Co.",
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/7919755/pexels-photo-7919755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    title: "Warm Woolen Scarf",
    size: "One Size",
    color: "Red",
    category: "Accessories",
    price: "$25.99",
    brand: "FashionGlam",
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/2229712/pexels-photo-2229712.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    title: "Men's Denim Jacket",
    size: "Large",
    color: "Blue",
    category: "Men's Jackets",
    price: "$69.99",
    brand: "DenimWorld",
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/8365688/pexels-photo-8365688.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    title: "Leather Crossbody Bag",
    size: "Medium",
    color: "Black",
    category: "Bags",
    price: "$55.50",
    brand: "ChicAccessories",
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/7651067/pexels-photo-7651067.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    title: "Casual Sneakers",
    size: "9",
    color: "White",
    category: "Footwear",
    price: "$49.95",
    brand: "StepUp",
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/4998599/pexels-photo-4998599.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    title: "Summer Maxi Dress",
    size: "Medium",
    color: "Floral Print",
    category: "Women's Dresses",
    price: "$55.00",
    brand: "Fashionista",
  },
];
