export const userRows = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    lastName: "Snow",
    firstName: "Jon",
    email: "johnsnow@gmail.com",
    phoneNumber: "",
    createdAt: 35,
    verified: true,
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    lastName: "Lannister",
    firstName: "Cersei",
    email: "cersei@gmail.com",
    phoneNumber: "",
    createdAt: 42,
    verified: true,
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    lastName: "Lannister",
    firstName: "Jaime",
    email: "lannister@gmail.com",
    phoneNumber: "",
    createdAt: 44,
    verified: true,
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    lastName: "Stark",
    firstName: "Arya",
    email: "stark@stark.com",
    phoneNumber: "",
    createdAt: 16,
    verified: true,
  },
  {
    id: 5,
    img: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    lastName: "Targaryen",
    firstName: "Daenerys",
    email: "targaryen@gmail.com",
    phoneNumber: "",
    createdAt: null,
    verified: true,
  },
  {
    id: 6,
    img: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    lastName: "Melisandre",
    firstName: null,
    email: "melisandre@gmail.com",
    phoneNumber: "",
    createdAt: 150,
    verified: true,
  },
  {
    id: 7,
    img: "https://images.pexels.com/photos/670720/pexels-photo-670720.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    lastName: "Clifford",
    firstName: "Ferrara",
    email: "clifford@gmail.com",
    phoneNumber: "",
    createdAt: 44,
    verified: true,
  },
  {
    id: 8,
    img: "",
    lastName: "Frances",
    firstName: "Rossini",
    email:
      "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    phoneNumber: "frances@example.com",
    createdAt: 36,
    verified: true,
  },
  {
    id: 9,
    img: "https://images.pexels.com/photos/91224/pexels-photo-91224.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    lastName: "Roxie",
    firstName: "Harvey",
    email: "roxie@roxie.com",
    phoneNumber: "",
    createdAt: 65,
    verified: true,
  },
];
